### ISSUE TITLE
Problem starting a node to connect to testnets

### ISSUE THREAD

**Issue by juntao** [tendermint/testnets#7]
I am following the instructions on the README.md, but something is missing ... Any help / pointer would appreciated. If there is an ommisson from the documentation, let me know and I can help fix it. Thanks.

https://github.com/tendermint/testnets

However, this command fails:

BCHOME="$HOME/testnets/mercury" basecoin start
No genesis file at ...

Next, I tried:

BCHOME="$HOME/testnets/mercury/basecoin" basecoin start
The genesis file has no validators

Finally, as a last resort, I tried:

BCHOME="$HOME/testnets/mercury/tendermint" basecoin start
panic: Tendermint state.AppHash does not match AppHash after replay. Got BE3CF7B8282F2FE4CBF169D577F5B1E48C3D9D10, expected

goroutine 1 [running]:
github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).checkAppHash(0xc4201336b0, 0xc420144960, 0x14, 0x14, 0x6, 0x6)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/consensus/replay.go:375 +0x264
github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc4201336b0, 0xc420144960, 0x14, 0x14, 0x1, 0x10dfcc0, 0xc420060c00, 0x0, 0x14, 0x0, ...)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/consensus/replay.go:265 +0xbb7
github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc4201336b0, 0x10dfcc0, 0xc420060c00, 0x0, 0x10daea0)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/consensus/replay.go:237 +0x4f4
github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc420060c00, 0xc42011fe80, 0x15)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:108 +0x89e
github.com/tendermint/basecoin/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc420060c00, 0x10dae00, 0x0, 0x0)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tmlibs/common/service.go:105 +0x482
github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/node.NewNode(0xc4204334a0, 0xc42043ad20, 0x10d1860, 0xc420145b20, 0x10daea0, 0xc420132f90, 0xc0b1f4)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tendermint/node/node.go:87 +0x880
github.com/tendermint/basecoin/cmd/basecoin/commands.startTendermint(0xc42012e448, 0x2b, 0xc420431290, 0xc420144c60, 0x2)
	/home/vagrant/go/src/github.com/tendermint/basecoin/cmd/basecoin/commands/start.go:133 +0x29b
github.com/tendermint/basecoin/cmd/basecoin/commands.startCmd(0x111d2e0, 0x11438f8, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/tendermint/basecoin/cmd/basecoin/commands/start.go:103 +0xdf1
github.com/tendermint/basecoin/vendor/github.com/spf13/cobra.(*Command).execute(0x111d2e0, 0x11438f8, 0x0, 0x0, 0x111d2e0, 0x11438f8)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/tendermint/basecoin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x111d0c0, 0x2, 0x2, 0xc420144c40)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/tendermint/basecoin/vendor/github.com/spf13/cobra.(*Command).Execute(0x111d0c0, 0xc4201502c0, 0x16)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/tendermint/basecoin/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x111d0c0, 0xd515e0, 0x2, 0xc420144ba0)
	/home/vagrant/go/src/github.com/tendermint/basecoin/vendor/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/home/vagrant/go/src/github.com/tendermint/basecoin/cmd/basecoin/main.go:22 +0x123

**Comment by zramsay** [comment]
the readme is a little bit outdated and will soon be consolidated with the [tendermint docs](http://tendermint.readthedocs.io/en/master/). In the meantime, you can try [connecting to the ethermint testnet](http://ethermint.readthedocs.io/en/develop/testnets/index.html). There are also [these tools](https://github.com/tendermint/tools) you can try for deploying your own testnet.

**Comment by juntao** [comment]
Thank you Zach!

**Comment by zramsay** [comment]
no problem! hope that helped :)
